Fix: Resolve Success.tsx style error
The error `src/pages/Success.tsx(81,14): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'` was caused by incorrect usage of the `style` tag. This commit fixes the error.